#spring:
#  cloud:
#    config:
#      server:
#        native:
#          search-locations: classpath:/shared
#  profiles:
#     active: native
#  application:
#    name: config-server
#
#server:
#  port: 8769


server:
  port: 8769

# remote git
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/bruobuqi/springcloud/tree/master/Spring%20Cloud%20Config
          searchPaths: respo
          username:
          password:
      label: master
  application:
    name: config-server